SOURCEDIR = ./
OUTDIR = ./Release/

RM = rm

CXX = icc
#CXX = g++

OBJECTS = ${OUTDIR}/Tier.o ${OUTDIR}/Stall.o ${OUTDIR}/main.o

${OUTDIR}/FarmAccounting_lnx86_64.exe : ${OBJECTS}
	${CXX} ${EXTRA_CFLAGS} ${INCDIR} ${OBJECTS} ${LIBDIR} -std=c++11 -g -fPIC -Wl,-Bdynamic  -lpthread -lm -o $@
	
${OUTDIR}/%.o : ${SOURCEDIR}/%.cpp
	${CXX} -c ${EXTRA_CFLAGS} -fPIC -w -Wno-deprecated -DTYPENAME=typename -D_LINUX_SOURCE -DSMA_GNUC -DFOR_TRAIL -DHAS_BOOL -DASSERT_ENABLED -D_BSD_TYPES -D_BSD_SOURCE -D_GNU_SOURCE -D_POSIX_SOURCE -D_XOPEN_SOURCE_EXTENDED -D_XOPEN_SOURCE -DHAVE_OPENGL -DHKS_OPEN_GL -DGL_GLEXT_PROTOTYPES -DMULTI_THREADING_ENABLED -D_REENTRANT -DABQ_MPI_SUPPORT -DABQ_MPI_PMPI -DBIT64 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 ${INCDIR} $< -o $@

clean :
	@ ${RM} -rf ${OUTDIR}/*.o ${OUTDIR}/*.exe